included:
  - WeatherForecast

opt_in_rules: # some rules are only opt-in
  - empty_count
  - explicit_init
  - closure_spacing
  - overridden_super_call
  - redundant_nil_coalescing
  - private_outlet:
      allow_private_set: true
  - nimble_operator
  - attributes
  - operator_usage_whitespace
  - closure_end_indentation
  - first_where
  - sorted_imports
  - object_literal
  - number_separator
  - prohibited_super_call
  - fatal_error_message
  - vertical_parameter_alignment_on_call
  - let_var_whitespace
  - unneeded_parentheses_in_closure_argument
  - extension_access_modifier
  - pattern_matching_keywords
  - array_init

disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
  - line_length
  - function_parameter_count
  - function_body_length 
  - cyclomatic_complexity
  - identifier_name
  - large_tuple
  - class_delegate_protocol
  - weak_delegate
  - force_cast
